In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('accessibilit-economica-alloggi-26-paesi-1975-2025.csv')

In [5]:
data.head()

,country,iso,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy
0,Australia,AUS,1975,2.83,7.19,21.89,55.72,39.29
1,Australia,AUS,1976,3.19,8.11,21.65,55.04,39.34
2,Australia,AUS,1977,3.48,8.91,21.43,54.88,39.05
3,Australia,AUS,1978,3.75,9.85,21.28,55.91,38.06
4,Australia,AUS,1979,4.20,10.80,21.75,55.94,38.88

In [8]:
data.describe()

,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy
count,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000
mean,2000.000000,45.946131,46.018469,73.161395,73.154487,102.955437
std,14.725155,33.065122,28.423394,30.650240,18.670035,60.875057
min,1975.000000,0.000000,0.000000,16.140000,16.190000,37.300000
25%,1987.000000,16.982500,22.335000,49.110000,58.662500,75.522500
50%,2000.000000,42.140000,44.825000,71.760000,73.460000,96.020000
75%,2013.000000,69.872500,68.815000,97.075000,88.962500,109.497500
max,2025.000000,162.300000,106.490000,181.470000,107.730000,725.910000

In [13]:
data.isnull().sum().value_counts()

0    8
Name: count, dtype: int64

In [17]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1326 entries, 0 to 1325
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country                          1326 non-null   str
 1   iso                              1326 non-null   str
 2   year                             1326 non-null   int64
 3   house_price_index                1326 non-null   float64
 4   personal_disposable_income       1326 non-null   float64
 5   real_house_price_index           1326 non-null   float64
 6   real_personal_disposable_income  1326 non-null   float64
 7   affordability_proxy              1326 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 83.0 KB

In [19]:
data.groupby('country')['real_house_price_index'].mean().sort_values(ascending=False)

country
Japan          118.740980
Italy          105.583725
S. Korea       105.152745
Spain           96.357059
S. Africa       94.259412
Germany         94.001961
Colombia        91.568824
Finland         91.294706
Croatia         76.936471
Switzerland     72.631569
France          72.042941
Denmark         69.960588
Belgium         67.693529
Portugal        64.988039
Slovenia        64.312157
UK              62.285686
US              61.968235
Sweden          61.907451
Netherlands     61.354118
Norway          59.175686
Ireland         56.621961
Luxembourg      51.890980
Canada          51.565098
Australia       50.605294
Israel          50.404314
New Zealand     48.892745
Name: real_house_price_index, dtype: float64

In [20]:
data.isnull().sum()

country                            0
iso                                0
year                               0
house_price_index                  0
personal_disposable_income         0
real_house_price_index             0
real_personal_disposable_income    0
affordability_proxy                0
dtype: int64

In [21]:
data.duplicated().sum()

np.int64(0)

In [23]:
data['country'].value_counts()

country
Australia      51
Belgium        51
Canada         51
Switzerland    51
Germany        51
Denmark        51
Spain          51
Finland        51
France         51
UK             51
Ireland        51
Italy          51
Japan          51
S. Korea       51
Luxembourg     51
Netherlands    51
Norway         51
New Zealand    51
Sweden         51
US             51
S. Africa      51
Croatia        51
Israel         51
Slovenia       51
Colombia       51
Portugal       51
Name: count, dtype: int64