In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('accessibilit-economica-alloggi-26-paesi-1975-2025.csv')

In [5]:
data.head()

,country,iso,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy
0,Australia,AUS,1975,2.83,7.19,21.89,55.72,39.29
1,Australia,AUS,1976,3.19,8.11,21.65,55.04,39.34
2,Australia,AUS,1977,3.48,8.91,21.43,54.88,39.05
3,Australia,AUS,1978,3.75,9.85,21.28,55.91,38.06
4,Australia,AUS,1979,4.20,10.80,21.75,55.94,38.88

In [8]:
data.describe()

,year,house_price_index,personal_disposable_income,real_house_price_index,real_personal_disposable_income,affordability_proxy
count,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000,1326.000000
mean,2000.000000,45.946131,46.018469,73.161395,73.154487,102.955437
std,14.725155,33.065122,28.423394,30.650240,18.670035,60.875057
min,1975.000000,0.000000,0.000000,16.140000,16.190000,37.300000
25%,1987.000000,16.982500,22.335000,49.110000,58.662500,75.522500
50%,2000.000000,42.140000,44.825000,71.760000,73.460000,96.020000
75%,2013.000000,69.872500,68.815000,97.075000,88.962500,109.497500
max,2025.000000,162.300000,106.490000,181.470000,107.730000,725.910000

In [12]:
data.isnull().sum().value_counts()

0    8
Name: count, dtype: int64